# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://dssatpitt.github.io
title: Digital Scholarship Services
email: uls-digitalscholarshipservices@pitt.edu
author: Matt Burton
description: > # "Digital Scholarship Services is a unit of the University Library System at the University of Pittsburgh."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/DSSatPitt
  - title: github
    url: https://github.com/DSSatPitt
